### ISSUE TITLE
Replayer

### ISSUE THREAD

**Issue by okputadora** [mathematicalthinking/vmt#13]
## Todo
- [x] create a log that combines event and chat data in chronological order
- [x] create a function that checks the time between log entries and fast forwards when necessary 
- [x] capture entries/exits to/from room as events so we can reconstruct current members, we cant just pass the room.currentMembers
- [x] Build UI for replay controls 
- [x] calculate "Display Duration" this differs from the actual duration because we don't want long periods of inactivity to be part of the display, they should be little tick in the progress bar that tell you how much time elapsed on hover
- [x] skip periods of inactivity, mark them in the progress bar,
- [x] build a scrollable "log" that will serve as a brief description of each event. As the user drags the time index the log will scroll & vice versa 
- [x] ~~In geogebra, when you create a triangle, each point creates an event, as well as each line and the whole shape it self. So when you click three points to construct a triangle it creates 7 events (actually more becuase it renames all of the lines once they're connected---anyway) we really only want this to be tree events. If the events are within 50ms of each other we can assume the events were of the type just described and we should squash them into one event~~ Unsure if we want to implement this
- [x] when we set the state of the graph it includes the dimensions of the window. If students work in the room on one size screen and then a teacher replays the activity on a different size screen, sometime the events will be happening off screen. --- we should try to extract window size information from the "event" and let the teacher set their own view size
- [x] user in control should appear bigger than the other users in the current member box
